force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organizer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Write email</description>
    <inlineHelpText>Please Write email</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <label>Events</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>Select the seats</description>
    <inlineHelpText>You need to select the seats</inlineHelpText>
    <label>Max Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>write Name</description>
    <inlineHelpText>write Address</inlineHelpText>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Select date and time</description>
    <inlineHelpText>You need to select date and time</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>Write company</description>
    <inlineHelpText>please write company</inlineHelpText>
    <label>Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>write email</description>
    <inlineHelpText>Please write email</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Speaker__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>write phone no.</description>
    <inlineHelpText>Please write phone no,</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/EventWebService.cls
@RestResource(urlMapping='/v1/EventWebService/')

global class EventWebService {

@httpGet

global static List<EventWrapper> doGetMethod(){

  List<EventWrapper> eventWrappers = new List<EventWrapper>();

    List<Events__c> events = [SELECT Name__c, Start__c, Max_Seats__c,Organizer__r.Name , Organizer__r.Email__c FROM Events__c];

    for (Events__c event : events) {

      EventWrapper eventWrapper = new EventWrapper();

      eventWrapper.event = new Events__c();

      eventWrapper.event.Name__c = event.Name__c;

      eventWrapper.event.Start__c = event.Start__c;

      eventWrapper.event.Max_Seats__c = event.Max_Seats__c;

      eventWrapper.event_organizer = new Event_Organizer__c();

      eventWrapper.event_organizer.Name = event.Organizer__r.Name;

      eventWrapper.event_organizer.Email__c = event.Organizer__r.Email__c;

      eventWrappers.add(eventWrapper);

    }


    return eventWrappers;

  }

  @httpPost

  global static String doPostMethod(String Name, String email, String phone, String company){

    try

    {

    Speaker__c spkr= new Speaker__c(Name =Name, Email__c = email, Phone__c = phone, Company__c = company);

    insert spkr;

    return '200';

    }

    catch(Exception e){

      return '400';

    }

  }

  // Wrapper class for events

  global class EventWrapper {

    global Events__c event;

    global Event_Organizer__c event_organizer;

  }

}