force-app/main/default/objects/Attendees__c/Attendees__c.object-meta.xml
<CustomObject>
    <label>Attendees</label>
    <nameField>
        <label>Attendees Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendees__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Write Email</description>
    <inlineHelpText>Please write email</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Attendees__c/fields/Location_Address_Book__c.field-meta.xml
<CustomField>
    <fullName>Location_Address_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location (Address Book)</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event-Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event-Attendee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendees__c.field-meta.xml
<CustomField>
    <fullName>Attendees__c</fullName>
    <description>Write Attendees</description>
    <inlineHelpText>please Write Attendees</inlineHelpText>
    <label>Attendees</label>
    <referenceTo>Attendees__c</referenceTo>
    <relationshipLabel>Event-Attendee</relationshipLabel>
    <relationshipName>Event_Attendee</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Events__c.field-meta.xml
<CustomField>
    <fullName>Events__c</fullName>
    <description>Write event MD</description>
    <inlineHelpText>Please write event MD</inlineHelpText>
    <label>Events</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipLabel>Event-Attendee</relationshipLabel>
    <relationshipName>Event_Attendee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <label>Events</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Location_Address_Book__c.field-meta.xml
<CustomField>
    <fullName>Location_Address_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location (Address Book)</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>write Name</description>
    <inlineHelpText>write Address</inlineHelpText>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Select date and time</description>
    <inlineHelpText>You need to select date and time</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location (Address Book)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EventAttendeeTriggerHandler.cls
public class EventAttendeeTriggerHandler {
    public static void AttendeeEmailSend(List<Event_Attendee__c> EventAttendeeNewRecords) {
        List<Messaging.SingleEmailMessage> Emails = new List<Messaging.SingleEmailMessage>();
       
            Set<Id> eventIds = new Set<Id>();
            Set<Id> attendeeIds = new Set<Id>();
            for (Event_Attendee__c eventAttendeeNewRecord : EventAttendeeNewRecords) {
                
                    eventIds.add(eventAttendeeNewRecord.Events__c);
                    attendeeIds.add(eventAttendeeNewRecord.Attendees__c);
            }
            
            Map<Id, Events__c> eventMap = new Map<Id, Events__c>([
                SELECT Name__c, Start__c, 	Location_Address_Book__r.Name, Organizer__r.Name 
                FROM Events__c 
                WHERE Id IN :eventIds
            ]);
            
            Map<Id, Attendees__c> attendeeMap = new Map<Id, Attendees__c>([
                SELECT Name, Email__c 
                FROM Attendees__c 
                WHERE Id IN :attendeeIds]);
        
        for (Event_Attendee__c eventAttendeeNewRecord : EventAttendeeNewRecords) {
           
            
                if (eventAttendeeNewRecord.Events__c == null && eventAttendeeNewRecord.Attendees__c == null) {
                    continue;
                }
    
                    Events__c event = eventMap.get(eventAttendeeNewRecord.Events__c);
                    Attendees__c attendee = attendeeMap.get(eventAttendeeNewRecord.Attendees__c);
                    
                    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                    email.setToAddresses(new String[]{attendee.Email__c});
                    email.setSubject('Pass for the "' + event.Name__c + '"');
                    email.setPlainTextBody('Dear ' + attendee.Name + ',\n\nThank you for registering for "' 
                                           + event.Name__c + '" which will be organized on '
                                           + event.Start__c.format('dd/mm/yyyy') + ' and will be held in '
                                           + event.Location_Address_Book__r.Name + '. We are excited to have you, see you at the event.\n\nThanks,\n'
                                           + event.Organizer__r.Name);
                    Emails.add(email);
           
            
        }
        
        try {
            Messaging.sendEmail(Emails);
        } catch (Exception e) {
            ErrorLogRecordingInsert.insertErrorLog(e.getMessage(), 'Error sending email');
        }
        
    }
}