force-app/main/default/objects/Attendees__c/Attendees__c.object-meta.xml
<CustomObject>
    <label>Attendees</label>
    <nameField>
        <label>Attendees Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendees__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Write Email</description>
    <inlineHelpText>Please write email</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Attendees__c/fields/Location_Address_Book__c.field-meta.xml
<CustomField>
    <fullName>Location_Address_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location (Address Book)</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event-Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event-Attendee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendees__c.field-meta.xml
<CustomField>
    <fullName>Attendees__c</fullName>
    <description>Write Attendees</description>
    <inlineHelpText>please Write Attendees</inlineHelpText>
    <label>Attendees</label>
    <referenceTo>Attendees__c</referenceTo>
    <relationshipLabel>Event-Attendee</relationshipLabel>
    <relationshipName>Event_Attendee</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Events__c.field-meta.xml
<CustomField>
    <fullName>Events__c</fullName>
    <description>Write event MD</description>
    <inlineHelpText>Please write event MD</inlineHelpText>
    <label>Events</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipLabel>Event-Attendee</relationshipLabel>
    <relationshipName>Event_Attendee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <label>Events</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>Select end date and time</description>
    <inlineHelpText>You need to select end date and time</inlineHelpText>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Live field</description>
    <inlineHelpText>You need to look for live</inlineHelpText>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Location_Address_Book__c.field-meta.xml
<CustomField>
    <fullName>Location_Address_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location (Address Book)</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>Select the seats</description>
    <inlineHelpText>You need to select the seats</inlineHelpText>
    <label>Max Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>write Name</description>
    <inlineHelpText>write Address</inlineHelpText>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Select date and time</description>
    <inlineHelpText>You need to select date and time</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location (Address Book)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EventAttendeeTriggerHandlerTest.cls
@isTest
public class EventAttendeeTriggerHandlerTest {
    
    @isTest
    static void testAttendeeEmailSend() {

        // Create a location record
        Location__c location = new Location__c();
        location.Name = 'Test Location';
        insert location;

         // Create an event record
        Events__c event = new Events__c();
        event.Name__c = 'Test Event';
        event.Start__c = Date.today();
        event.End__c = Date.today().addDays(60);
        event.Location_Address_Book__c = location.Id;
        
        event.Live__c = true; // Set to true to accept attendees
        event.Max_Seats__c = 100;
        insert event;

          // Create an attendee record
        Attendees__c attendee = new Attendees__c();
        attendee.Name = 'Test Attendee';
        attendee.Email__c = 'testattendee@example.com';
        insert attendee;
        // Create an event attendee record
        Event_Attendee__c eventAttendee = new Event_Attendee__c();
        eventAttendee.Events__c = event.Id;
        eventAttendee.Attendees__c = attendee.Id;

        List<Event_Attendee__c> eventAttendeeList = new List<Event_Attendee__c>();
        eventAttendeeList.add(eventAttendee);

        Test.startTest();
        // Call the static method to test it
        EventAttendeeTriggerHandler.attendeeEmailSend(eventAttendeeList);
        Test.stopTest();

        // Verify that the email was sent
        List<EmailMessage> sentEmails = [SELECT Id, ToAddress FROM EmailMessage];
        System.assertEquals(1, sentEmails.size());
        System.assertEquals('testattendee@example.com', sentEmails[0].ToAddress);
    }
}