force-app/main/default/objects/Attendees__c/Attendees__c.object-meta.xml
<CustomObject>
    <label>Attendees</label>
    <nameField>
        <label>Attendees Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendees__c/fields/Location_Address_Book__c.field-meta.xml
<CustomField>
    <fullName>Location_Address_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location (Address Book)</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event-Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event-Attendee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendees__c.field-meta.xml
<CustomField>
    <fullName>Attendees__c</fullName>
    <description>Write Attendees</description>
    <inlineHelpText>please Write Attendees</inlineHelpText>
    <label>Attendees</label>
    <referenceTo>Attendees__c</referenceTo>
    <relationshipLabel>Event-Attendee</relationshipLabel>
    <relationshipName>Event_Attendee</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Events__c.field-meta.xml
<CustomField>
    <fullName>Events__c</fullName>
    <description>Write event MD</description>
    <inlineHelpText>Please write event MD</inlineHelpText>
    <label>Events</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipLabel>Event-Attendee</relationshipLabel>
    <relationshipName>Event_Attendee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <label>Events</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Location_Address_Book__c.field-meta.xml
<CustomField>
    <fullName>Location_Address_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location (Address Book)</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location (Address Book)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AttendeeRegistrationController.cls
public with sharing class AttendeeRegistrationController {
    public Attendees__c att {get;set;}
    public Event_Attendee__c  evtAttendee{get;set;}
    public Location__c loc {get;set;}
    public String mstrId;
    public AttendeeRegistrationController() {
        mstrId = ApexPages.currentpage().getParameters().get('param1');
        att= new Attendees__c();
        evtAttendee = new Event_Attendee__c();
        loc=  new Location__c ();
        evtAttendee.Events__c = mstrId;
    }
    public PageReference save(){
    insert loc;
    att.Location_Address_Book__c=loc.Id;
    insert att;
    evtAttendee.Attendees__c= att.Id;
    insert evtAttendee;
    return new PageReference('/apex/AttendeeRegistrationController').setRedirect(true);
    }
}