force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event-Speaker</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Event-Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event-Speaker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Events__c.field-meta.xml
<CustomField>
    <fullName>Events__c</fullName>
    <description>write events</description>
    <inlineHelpText>please Write events</inlineHelpText>
    <label>Events</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipLabel>Event-Speaker</relationshipLabel>
    <relationshipName>Event_Speaker</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>Write speaker</description>
    <inlineHelpText>please Write speaker</inlineHelpText>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event-Speaker</relationshipLabel>
    <relationshipName>Event_Speaker</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <label>Events</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Location_Address_Book__c.field-meta.xml
<CustomField>
    <fullName>Location_Address_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location (Address Book)</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>write Name</description>
    <inlineHelpText>write Address</inlineHelpText>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Select date and time</description>
    <inlineHelpText>You need to select date and time</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location (Address Book)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EventSpeakerDetailsController.cls
public with sharing class EventSpeakerDetailsController {

    public String MstrId{get;set;}
    public Events__c evt{get;set;}
    public List<Event_Speaker__c> evtSpkr{get;set;}

    // public Speaker__c spkr{get;set;}

    public EventSpeakerDetailsController() {
        MstrId = ApexPages.currentPage().getParameters().get('id');
        evt = [Select id, Name__c, Organizer__r.Name, Location_Address_Book__r.Name, Start__c from Events__c where id=:MstrId LIMIT 1];
        evtSpkr = [Select id, Events__r.Name__c, Speaker__r.Name, Speaker__r.Profile_URL__c, Speaker__r.About_Me__c from Event_Speaker__c WHERE Events__c = :MstrId];
        // spkr = new Speaker__c();
    }

    // public EventSpeakerDetailsController(ApexPages.StandardController stdController) {
    //     this.evt = (Event__c)stdController.getRecord();
    // }

    public PageReference saveAsAttendee(){
        return new PageReference('/apex/AttendeeRegistrationController?param1='+MstrId).setRedirect(true);
    }

    public PageReference saveAsSpeaker(){
        return new PageReference('/apex/SpeakerRegistrationController?param1='+MstrId).setRedirect(true);
    }
}