force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event-Speaker</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Event-Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event-Speaker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Events__c.field-meta.xml
<CustomField>
    <fullName>Events__c</fullName>
    <description>write events</description>
    <inlineHelpText>please Write events</inlineHelpText>
    <label>Events</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipLabel>Event-Speaker</relationshipLabel>
    <relationshipName>Event_Speaker</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>Write speaker</description>
    <inlineHelpText>please Write speaker</inlineHelpText>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event-Speaker</relationshipLabel>
    <relationshipName>Event_Speaker</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <label>Events</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/SpeakerRegistrationController.cls
public with sharing class SpeakerRegistrationController {

    public Speaker__c spk{get;set;}
    public Event_Speaker__c espk{get;set;}
    //public Events__c evt{get;set;}
    public String mstrId;
    

    public SpeakerRegistrationController() {
        mstrId = ApexPages.currentpage().getParameters().get('param1');
        spk=new Speaker__c();
        espk=new Event_Speaker__c();
        //evt=new Events__c();
        espk.Events__c=mstrId;
    }
    public PageReference save() 
	{
    	insert spk;
        espk.Speaker__c=spk.ID;
        
        insert espk;
       
       
       
		return new PageReference('/apex/SpeakerRegistrationController').setRedirect(true);
	}
}