force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <label>Events</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>Select end date and time</description>
    <inlineHelpText>You need to select end date and time</inlineHelpText>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Live field</description>
    <inlineHelpText>You need to look for live</inlineHelpText>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DeleteEventRecords.cls
public with sharing class DeleteEventRecords implements Database.Batchable<SObject>  {
    public Database.QueryLocator start(Database.BatchableContext batchContext){
        String query = 'Select id from Events__c where Live__c = true AND End__c < LAST_N_MONTHS:2';
        return Database.getQueryLocator(query);

    } 

    public void execute(Database.BatchableContext batchContext, List<Events__c> listEvt){
         delete listEvt;
        }
    

    public void finish(Database.BatchableContext batchContext){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        mail.setSubject('Batch has been processed');
        List<String> toAddress = new List<String>();
        toAddress.add('aman.kumar@mirketa.com');
        mail.setToAddresses( toAddress );
        mail.setSenderDisplayName('Organizer');
        
        mail.setHtmlBody('The records have been deleted.');
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage> {mail};
        Messaging.sendEmail(emails);
    }
}