force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <label>Events</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>Select end date and time</description>
    <inlineHelpText>You need to select end date and time</inlineHelpText>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>Select the event type</description>
    <inlineHelpText>You need to select the event type</inlineHelpText>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Events__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>select the Frequency</description>
    <inlineHelpText>You need to select the Frequency</inlineHelpText>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Recurring__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Events__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Live field</description>
    <inlineHelpText>You need to look for live</inlineHelpText>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <description>Select the seats</description>
    <inlineHelpText>You need to select the seats</inlineHelpText>
    <label>Max Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>write Name</description>
    <inlineHelpText>write Address</inlineHelpText>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Recurring__c.field-meta.xml
<CustomField>
    <fullName>Recurring__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Write Recurring</description>
    <inlineHelpText>Write Recurring</inlineHelpText>
    <label>Recurring?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Select date and time</description>
    <inlineHelpText>You need to select date and time</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DeleteEventRecordsTest.cls
@isTest
public class DeleteEventRecordsTest {
    @testSetup
    public static void testSetupData() {
        List<Events__c> eventList = new List<Events__c>();
        for(Integer i=0; i<=200; i++){
            Events__c event = new Events__c(
                Name__c = 'New Event #'+i+1,
                Event_Type__c = 'Virtual',
                Frequency__c = 'Weekly',
                Max_Seats__c = 199,
                Recurring__c = true,
                Live__c = true,
                Start__c = System.now().addMonths(-4),
                End__c = System.now().addDays(3).addMonths(-4)
            );
            eventList.add(event);
        }
        insert eventList;
        List<Events__c> eventList1 = new List<Events__c>();
        for(Integer i=0; i<200; i++){
            Events__c event = new Events__c(
                Name__c = 'New Event #'+i+1,
                Event_Type__c = 'Virtual',
                Frequency__c = 'Weekly',
                Max_Seats__c = 199,
                Recurring__c = true,
                Live__c = false,
                Start__c = System.now().addMonths(-4),
                End__c = System.now().addDays(3).addMonths(-4)
            );
            eventList1.add(event);
        }
        insert eventList1;
       
    }

    @isTest
    static void sendDeleteEventTest() {
        Test.startTest();
        String jobId = Database.executeBatch(new DeleteEventRecords(), 250);
        Test.stopTest();
        
        List<Events__c> eventlist=[select id, Name from Events__c WHERE Live__c =true AND End__c < LAST_N_MONTHS:2 ];
        System.assertEquals(0,eventlist.size());
        List<Events__c> eventlist1=[select id,Name from Events__c];
        System.assertEquals(200,eventlist1.size());
    }
}